#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin

usage() {
    cat << EOF
    usage: $(basename $0) action
        action: start or stop to enable/disable slave services
EOF
}

set_berofos_to_slave_state() {
    xivo-berofos -q --syslog slave
}

set_berofos_to_master_state() {
    xivo-berofos -q --syslog master
}

enable_service() {
    set_berofos_to_slave_state
    xivo-service enable
    xivo-service start
    xivo-agentctl --no-fetch -c 'relog all'
}

disable_service() {
    xivo-service stop xivo
    xivo-service disable
    set_berofos_to_master_state
    xivo-service start
}

case $1 in
    start) enable_service;;
    stop)  disable_service;;
    *) usage;;
esac
