#!/bin/sh

usage() {
    cat << EOF
    usage: $(basename $0) action
        action: start or stop to enable/disable slave services
EOF
}

enable_asterisk() {
    grep -q RUNASTERISK=no /etc/default/asterisk
    if [ $? -eq 0 ]; then
        sed -i 's/RUNASTERISK=no/RUNASTERISK=yes/' /etc/default/asterisk
    fi
    if [ ! -f /var/run/asterisk/asterisk.pid ]; then
        /usr/sbin/invoke-rc.d asterisk start
    fi
}

disable_asterisk() {
    if [ -f /var/run/asterisk/asterisk.pid ]; then
        /usr/sbin/invoke-rc.d asterisk stop
    fi
    grep -q RUNASTERISK=yes /etc/default/asterisk
    if [ $? -eq 0 ]; then
        sed -i 's/RUNASTERISK=yes/RUNASTERISK=no/' /etc/default/asterisk
    fi
}

enable_ctid() {
    grep -q "startup=no" /etc/default/xivo-ctid
    if [ $? -eq 0 ]; then
        sed -i 's/startup=no/startup=yes/' /etc/default/xivo-ctid
    fi
    if [ ! -f /var/run/xivo-ctid.pid ]; then
        /usr/sbin/invoke-rc.d xivo-ctid start
    fi
}

disable_ctid() {
    if [ -f /var/run/xivo-ctid.pid ]; then
        /usr/sbin/invoke-rc.d xivo-ctid stop
    fi
    grep -q "startup=yes" /etc/default/xivo-ctid
    if [ $? -eq 0 ]; then
        sed -i 's/startup=yes/startup=no/' /etc/default/xivo-ctid
    fi
}

enable_monit() {
    grep -q "startup=0" /etc/default/monit
    if [ $? -eq 0 ]; then
        sed -i 's/startup=0/startup=1/' /etc/default/monit
    fi
    if [ ! -f /var/run/monit.pid ]; then
        /usr/sbin/invoke-rc.d monit start
    fi
}

disable_monit() {
    if [ -f /var/run/monit.pid ]; then
        /usr/sbin/invoke-rc.d monit stop
    fi
    grep -q "startup=1" /etc/default/monit
    if [ $? -eq 0 ]; then
        sed -i 's/startup=1/startup=0/' /etc/default/monit
    fi
}

set_berofos_to_slave_state() {
    /usr/sbin/xivo-berofos -q --syslog slave
}

set_berofos_to_master_state() {
    /usr/sbin/xivo-berofos -q --syslog master
}

enable_service() {
    enable_asterisk
    enable_ctid
    enable_monit
    set_berofos_to_slave_state
}

disable_service() {
    set_berofos_to_master_state
    disable_monit
    disable_ctid
    disable_asterisk
}

case $1 in
    start) enable_service;;
    stop)  disable_service;;
    *) usage;;
esac
