#!/usr/bin/php
<?php

$ini = '/etc/pf-xivo/web-interface/xivo.ini';
$max = 7200;

if(is_file($ini) === true
&& is_readable($ini) === true
&& ($data = parse_ini_file($ini,true)) !== false
&& isset($data['session'],$data['session']['time']) === true
&& ctype_digit($data['session']['time']) === true
&& $data['session']['time'] > 0)
	$max = $data['session']['time'];

exit((string) ceil($max / 60));

?>
