#!/bin/sh

AST_ETC_PATH="/etc/asterisk"
AST_SPOOL_PATH="/var/spool/asterisk"
AST_VARLIB_PATH="/var/lib/asterisk"
WAZO_VARLIB_PATH="/var/lib/wazo"

SHARED_PATHS="${AST_ETC_PATH}
              ${AST_SPOOL_PATH}/fax
              ${AST_SPOOL_PATH}/monitor
              ${AST_VARLIB_PATH}/moh
              ${AST_VARLIB_PATH}/sounds/custom
              ${WAZO_VARLIB_PATH}
              ${WAZO_VARLIB_PATH}/sounds
              ${WAZO_VARLIB_PATH}/sounds/tenants"

echo "${SHARED_PATHS}" | while read SHARED_PATH;
do
    chown -R asterisk:www-data "${SHARED_PATH}"
    find "${SHARED_PATH}" -type d -exec chmod 2775 '{}' \;
    find "${SHARED_PATH}" -type f -exec chmod 660 '{}' \;
done;
