#!/usr/bin/python3
# Copyright 2016 Avencall
# SPDX-License-Identifier: GPL-3.0+

import configparser

FILENAME = '/etc/odbcinst.ini'


c = configparser.ConfigParser(interpolation=None)
c.optionxform = str

with open(FILENAME) as fobj:
    c.read_file(fobj)

modified = False

if 'ODBC' in c:
    if 'Pooling' in c['ODBC']:
        del c['ODBC']['Pooling']
        modified = True

    if not c['ODBC']:
        del c['ODBC']
        modified = True

if modified:
    with open(FILENAME, 'w') as fobj:
        c.write(fobj)
