#!/bin/sh

SLAVE_IP=$1
DB_NAME='asterisk'
SLAVE_BACKUP='out_slave_backup.sql'
MASTER_BACKUP='out_master_backup.sql'
DUMP='replication.sql'
SLAVE_CHECK='out_slave_check.sql'
EXCLUDE_TABLES='\
    -T call_log \
    -T call_log_id_seq \
    -T cel \
    -T cel_id_seq \
    -T queue_log \
    -T queue_log_id_seq \
    -T session \
    -T stat_agent \
    -T stat_agent_id_seq \
    -T stat_agent_periodic \
    -T stat_agent_periodic_id_seq \
    -T stat_call_on_queue \
    -T stat_call_on_queue_id_seq \
    -T stat_queue \
    -T stat_queue_id_seq \
    -T stat_queue_periodic \
    -T stat_queue_periodic_id_seq \
    -T dhcp \
    -T dhcp_id_seq \
    -T mail \
    -T mail_id_seq \
    -T monitoring \
    -T monitoring_id_seq \
    -T netiface \
    -T netiface_id_seq \
    -T resolvconf \
    -T resolvconf_id_seq \
'
PG_DUMP_OPTIONS="--data-only $EXCLUDE_TABLES"

panic() {
    echo "Slave replication failed: $*" | mutt root@localhost
    echo "Slave replication failed: $*"
    exit 1
}

backup_slave() {
    slave_backup=$1
    slave_ip=$2

    su postgres -c "pg_dump --host $slave_ip $PG_DUMP_OPTIONS $DB_NAME -f $slave_backup"
    if [ $? -ne 0 ]; then
        panic "Slave down"
    fi
}

backup_master() {
    master_backup=$1

    su postgres -c "pg_dump $PG_DUMP_OPTIONS $DB_NAME -f $master_backup"
    if [ $? -ne 0 ]; then
        panic "Could not dump master"
    fi
    asterisk -rx "module reload cel_pgsql.so"
}

generate_dump() {
    master_backup=$1
    dump=$2
    truncate_cmd="TRUNCATE $(grep '^COPY' $master_backup | cut -f2 -d\  | paste -sd ',');"

    echo "BEGIN;" > $dump
    echo $truncate_cmd >> $dump
    cat $master_backup >> $dump
    echo "COMMIT;" >> $dump
}

import_dump() {
    dump=$1
    slave_ip=$2

    su postgres -c "psql --host $SLAVE_IP $DB_NAME < $dump > /dev/null"
}

database_replicated() {
    master_dump=$1
    slave_dump=$2

    master_md5=$(sort $master_dump | md5sum | awk '{print $1}')
    slave_md5=$(sort $slave_dump | md5sum | awk '{print $1}')
    if [ "$master_md5" != "$slave_md5" ]; then
        return 1
    fi
    return 0
}

main() {
    cd /tmp
    backup_slave $SLAVE_BACKUP $SLAVE_IP
    backup_master $MASTER_BACKUP
    generate_dump $MASTER_BACKUP $DUMP
    import_dump $DUMP $SLAVE_IP

    backup_slave $SLAVE_CHECK $SLAVE_IP
    if ! database_replicated $MASTER_BACKUP $SLAVE_CHECK; then
        import_dump $SLAVE_BACKUP $SLAVE_IP
        panic "md5sum didnt match"
    fi

    echo "Slave replication completed succesfully"

    rm -f $DUMP
    rm -f $SLAVE_CHECK
}

if [ -z $SLAVE_IP ]; then
    echo "usage: $(basename $0) slave_ip"
    exit 1
fi

main
