#!/usr/bin/python3
# Copyright 2016 Avencall
# SPDX-License-Identifier: GPL-3.0+

import configparser

FILENAME = '/etc/odbcinst.ini'


c = configparser.ConfigParser(interpolation=None)
c.optionxform = str

with open(FILENAME) as fobj:
    c.read_file(fobj)

modified = False

if 'ODBC' in c:
    odbc_section = c['ODBC']
    if 'Pooling' in odbc_section:
        del odbc_section['Pooling']
        modified = True

    if not odbc_section:
        del c['ODBC']
        modified = True

if 'PostgreSQL ANSI' in c:
    psqla_section = c['PostgreSQL ANSI']
    if psqla_section.get('CommLog') != '0':
        psqla_section['CommLog'] = '0'
        modified = True

if modified:
    with open(FILENAME, 'w') as fobj:
        c.write(fobj)
