#!/bin/sh

SLAVE_IP=$1
if [ -z $SLAVE_IP ]; then
    echo "No IP specified"
    echo "Usage: $(basename $0) ip_addr"
fi
DB_NAME='asterisk'
SLAVE_BACKUP='out_slave_backup.sql'
PG_DUMP_OPTIONS='-T cel -T cel_id_seq'

panic() {
    echo "Slave replication failed: $*" | mutt root@localhost
    exit 1
}

cd /tmp

su postgres -c "pg_dump -h $SLAVE_IP -c $DB_NAME > $SLAVE_BACKUP"
if [ $? -ne 0 ]; then
    panic "Slave down"
fi

su postgres -c "pg_dump -c $PG_DUMP_OPTIONS $DB_NAME > out_master.sql"
asterisk -rx "module reload cel_pgsql.so"

su postgres -c "psql -h $SLAVE_IP $DB_NAME < out_master.sql > /dev/null"

su postgres -c "pg_dump -h $SLAVE_IP -c $PG_DUMP_OPTIONS $DB_NAME > out_slave.sql"

master_md5=$(cat out_master.sql | sort > out_master.sorted.sql &&  md5sum out_master.sorted.sql | awk '{print $1}')
slave_md5=$(cat out_slave.sql | sort > out_slave.sorted.sql && md5sum out_slave.sorted.sql | awk '{print $1}')

if [ "$master_md5" != "$slave_md5" ]; then
    su postgres -c "cat $SLAVE_BACKUP | psql -h $SLAVE_IP $DB_NAME"
    rm -f out_*.sql
    panic "md5sum didnt match"
else
    echo "Slave replication completed succesfully"
    rm -f out_*.sql
fi
