#!/bin/bash
set -e
monit_default="/etc/default/monit"
xivo_installed_version=$(sed 's/-rc.*//' /usr/share/pf-xivo/XIVO-VERSION)
xivo_candidate=$(apt-cache policy pf-xivo | grep Candidate | awk '{print $2}' | cut -d: -f2)
upgrading_tool="apt-get"

stop_monit () {
    sed -i 's/startup=1/startup=0/' $monit_default
    invoke-rc.d monit stop
}

start_monit () {
    sed -i 's/startup=0/startup=1/' $monit_default
    invoke-rc.d monit start
}

restart_xivo () {
    echo "Restarting xivo"
    services="postgresql dahdi xivo-confgend pf-xivo-agid asterisk xivo-ctid"
    for service in $services; do
        invoke-rc.d $service stop
        invoke-rc.d $service start
    done

}

upgrading_xivo () {
    echo "upgrading xivo"
    echo "updating package list"
    apt-get update
    echo "upgrading package"
    $upgrading_tool dist-upgrade
    restart_xivo
}

stop_monit

upgrading_xivo

start_monit
