#!/bin/bash
action=$1
services="dahdi xivo-confgend pf-xivo-provd pf-xivo-agid asterisk xivo-ctid nginx"

usage() {
    cat << EOF
    usage : $0 action
    availables actions :
        stop  : stop all xivo services
        start : stop all xivo services

    impacted services : $services
EOF
    exit 0
}

xivo_start() {
    /sbin/iptables -I INPUT 1 -p udp --dport 5060 -j DROP
    for service in $services; do
        /usr/sbin/invoke-rc.d $service start
    done
    status=$(asterisk -rx 'core waitfullybooted')
    while [ "$status" != "Asterisk has fully booted." ]; do
        sleep 1 
        status=$(asterisk -rx 'core waitfullybooted')
    done
    /sbin/iptables -D INPUT -p udp --dport 5060 -j DROP
}

xivo_stop() {
    /sbin/iptables -I INPUT 1 -p udp --dport 5060 -j DROP
    for service in $services; do
        /usr/sbin/invoke-rc.d $service stop
    done
    /sbin/iptables -D INPUT -p udp --dport 5060 -j DROP
}

xivo_restart() {
    xivo_stop;;
    xivo_start;;
}
case $action in
    restart) xivo_restart;;
    start)   xivo_start;;
    stop)    xivo_stop;;
    *) usage;;
esac
